import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { materialize, type IdentityAlias, type Material } from './catalogue.ts';
import { makeContext, canonical } from './structured/common.ts';
import { deriveStructured } from './structured/index.ts';
import { inventory, type CorpusBody } from '../report/inventory.ts';
import { publicArtifact } from '../validate/index.ts';
import type { AutomationEnvelope, AutomationRecord, Mechanics, VersionLock } from '../protocol.ts';
import type { InputManifest } from '../fetch/manifest.ts';
import { applyCorrections, type InputCorrection } from './corrections.ts';
import { TOOL_VERSION } from '../version.ts';
import { coverage, coverageMarkdown } from '../report/coverage.ts';
const kindMap:Record<string,string>={classFeature:'feature',subclassFeature:'feature',optionalfeature:'feature',subrace:'race',baseitem:'item',magicvariant:'item',charoption:'feature',reward:'feature',psionic:'feature',boon:'feature',action:'rule',sense:'rule',skill:'rule',language:'rule',itemMastery:'feature',itemProperty:'rule',itemType:'rule',itemGroup:'item',variantrule:'rule',disease:'condition'};
/** Secondary legacy codec copied from DND-card-web 80c94e0; never the IR key. */
export function legacyEntryId(row:Material):string {
  const raw=row.raw,kind=kindMap[row.identity.kind]||row.identity.kind,category=row.identity.kind;
  return [row.namespace,kind,row.identity.source,raw.ENG_name||raw.name,raw.classSource,raw.className,raw.subclassSource,raw.subclassShortName,kind==='feature'?raw.level:undefined,raw.raceName,...(kind==='rule'?[category]:[]),...(raw._variantIdentity?[raw._variantIdentity]:[]),...(['itemGroup','magicvariant','status','disease'].includes(category)?[category]:[])].map(v=>String(v??'').trim().toLowerCase()).map(encodeURIComponent).join(':');
}
export function deriveCorpus(files:CorpusBody[],manifest:InputManifest,aliases:IdentityAlias[]=[],corrections:InputCorrection[]=[]):{envelope:AutomationEnvelope;diagnostics:ReturnType<typeof materialize>['diagnostics'];fields:Record<string,{seen:number;handled:number}>} {
  const material=materialize(files,aliases),lookup=files.find(file=>file.input.path==='data/generated/gendata-spell-source-lookup.json')?.body;
  const corrected=applyCorrections(material.rows,manifest,corrections);material.rows=corrected.rows;material.diagnostics.push(...corrected.diagnostics);
  for(const row of material.rows)if(row.identity.kind==='spell') {
    const book=lookup?.[row.identity.source.toLowerCase()];const item=book?.[String(row.raw.name||'').toLowerCase()]||book?.[String(row.raw.ENG_name||'').toLowerCase()];if(item?.class)row.raw={...row.raw,_spellClasses:item.class};
  }
  const ctx=makeContext(material.rows),fieldCounts:Record<string,{seen:number;handled:number}>={};
  const records:AutomationRecord[]=material.rows.map(row=>{
    const derived=deriveStructured(row,ctx);
    for(const field of Object.keys(row.raw)) {const cell=fieldCounts[field]||={seen:0,handled:0};cell.seen++;if(derived.handled.has(field))cell.handled++;}
    const hasMechanics=Object.values(derived.mechanics).some(value=>Array.isArray(value)?value.length>0:!!value&&Object.keys(value).length>0);
    // Structured presence cannot prove that the narrative has no remaining mechanics.
    // Review of the complete entry belongs to the overlay gate, not this derivation.
    const annotations=corrected.annotations.get(row.identity.key)||[];
    return {identity:row.identity,...(row.edition?{edition:row.edition}:{}),entryIds:[legacyEntryId(row)],verdict:'needsAnnotation',autoGenerated:true,provenance:[...row.files.map(ref=>({layer:'structured' as const,ref})),...annotations.map(note=>note.provenance)],...(annotations.length?{evidence:annotations[0].evidence}:{}),...(hasMechanics?{mechanics:derived.mechanics}:{}),unsupported:derived.unsupported};
  });
  const versionLock=inventory(files,manifest).versionLock;
  if(!versionLock.fetchedAt)throw Error('Missing fetchedAt in corpus version lock');
  const envelope:AutomationEnvelope={schemaVersion:1,protocol:3,versionLock:{...versionLock,toolVersion:TOOL_VERSION} as VersionLock,records};
  return {envelope,diagnostics:material.diagnostics,fields:fieldCounts};
}
const stable=(value:unknown)=>JSON.stringify(value,null,2)+'\n';
export async function deriveFiles(cache:string,out:string,manifest:InputManifest):Promise<ReturnType<typeof deriveCorpus>> {
  const files:CorpusBody[]=await Promise.all(manifest.inputs.map(async input=>({input,body:JSON.parse(await readFile(join(cache,input.namespace,input.path),'utf8'))})));
  const aliases:IdentityAlias[]=JSON.parse(await readFile(new URL('../../aliases/identities.json',import.meta.url),'utf8'));
  const corrections:InputCorrection[]=JSON.parse(await readFile(new URL('../../aliases/input-corrections.json',import.meta.url),'utf8'));
  const result=deriveCorpus(files,manifest,aliases,corrections);
  // G3 drafts are validated before write. Fail rather than silently delete bad mechanics.
  const artifact=publicArtifact(result.envelope);
  const report=coverage(artifact,result.diagnostics,'G3-structured-draft');
  await mkdir(out,{recursive:true});await writeFile(join(out,'automation.json'),stable(artifact));await writeFile(join(out,'derivation-diagnostics.json'),stable({phase:'G3-structured-draft',completeAutomationClaim:false,identityDiagnostics:result.diagnostics,fields:result.fields}));
  await writeFile(join(out,'coverage-report.json'),stable(report));await writeFile(join(out,'coverage-report.md'),coverageMarkdown(report));
  return result;
}
