import {beforeAll,afterAll,it,expect} from 'vitest';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
import {pathToFileURL} from 'node:url';
const root=new URL('..',import.meta.url),out=mkdtempSync(join(tmpdir(),'dnd-browser-module-'));
beforeAll(()=>{execFileSync(process.execPath,['scripts/browser-bundle.mjs',out],{cwd:root,stdio:'pipe'});},30000);
afterAll(()=>rmSync(out,{recursive:true,force:true}));
const run=(program:string)=>JSON.parse(execFileSync(process.execPath,['--experimental-strip-types','--input-type=module','-e',program],{cwd:root,stdio:'pipe',encoding:'utf8'}));
it('one hash-locked module exposes the same identities and formula behavior without runtime imports',()=>{
 const manifest=JSON.parse(readFileSync(join(out,'shared-files.json'),'utf8')),source=readFileSync(join(out,'identity.ts'),'utf8');expect(Object.keys(manifest.files)).toEqual(['identity.ts']);expect(createHash('sha256').update(source).digest('hex')).toBe(manifest.files['identity.ts']);expect(source).not.toMatch(/^import\b|require\(["']ajv/gm);
 const result=run(`import assert from 'node:assert/strict';import fs from 'node:fs';const m=await import(${JSON.stringify(pathToFileURL(join(out,'identity.ts')).href)});const fixture=JSON.parse(fs.readFileSync('fixtures/shared/identity.json'));for(const [a,b]of fixture.same)assert.equal(m.createIdentity(a).key,m.createIdentity(b).key);for(const [a,b]of fixture.different)assert.notEqual(m.createIdentity(a).key,m.createIdentity(b).key);for(const row of fixture.invalid)assert.throws(()=>m.createIdentity(row));assert.equal(m.evaluateFormula('max(1,@prof-1)+floor(@class.level/2)',{'@prof':3,'@class.level':5}),4);assert.throws(()=>m.parseFormula('@actor.hp'));console.log(JSON.stringify({same:fixture.same.length,different:fixture.different.length,invalid:fixture.invalid.length}));`);expect(result.same).toBeGreaterThan(0);expect(result.different).toBeGreaterThan(0);expect(result.invalid).toBeGreaterThan(0);
});
it('compiled strict checks retain producer rejection of corrupted schema, identities, conditions and references',()=>{
 const result=run(`import assert from 'node:assert/strict';import fs from 'node:fs';import * as producer from './src/validate/index.ts';const browser=await import(${JSON.stringify(pathToFileURL(join(out,'identity.ts')).href)});const row=JSON.parse(fs.readFileSync('fixtures/g2/e2-dwarf-phb.json'));const base={schemaVersion:1,protocol:3,versionLock:{kiweeChangelogVersion:'synthetic',kiweeChangelogDate:'2026-10-03',fetchedAt:'2026-10-03T00:00:00Z',foundryMigrationVersion:[3],toolVersion:'synthetic',inputs:[{url:'https://example.org/input',path:'input',namespace:'synthetic',role:'catalog',sha256:'a'.repeat(64),bytes:1}]},records:[row]};const changes=[e=>{},e=>delete e.protocol,e=>e.records.push(structuredClone(row)),e=>e.records[0].identity.key='forged',e=>e.records[0].entries=['Synthetic body'],e=>e.records[0].evidence={page:1,quote:'保密测试'},e=>e.records[0].mechanics.resources=[{key:'bad',max:{formula:'@actor.hp'},recovery:[]}],e=>e.records[0].mechanics.grants=[{type:'spell',fixed:[browser.createIdentity({kind:'spell',source:'XPHB',engName:'Synthetic'}).key]}],e=>e.records[0].mechanics.grants=[{type:'spell',fixed:[browser.createIdentity({kind:'spell',source:'PHB',engName:'Missing synthetic'}).key]}],e=>e.records[0].verdict='noMechanics',e=>e.records[0].unsupported=[{family:'synthetic',code:'unsupported'}],e=>e.records[0].mechanics.modifiers=[{target:'ability:str',op:'set',value:1,condition:{target:'unsupported',op:'eq',value:true}}]];for(const [i,change]of changes.entries()){const value=structuredClone(base);change(value);const a=producer.automationErrors(value).map(x=>[x.code,x.path]),b=browser.automationErrors(value).map(x=>[x.code,x.path]);assert.deepEqual(b,a);if(i===0)assert.equal(b.length,0);else assert.ok(b.length>0);assert.deepEqual(browser.snapshotRecordErrors(value.records[0]).map(x=>[x.code,x.path]),producer.snapshotRecordErrors(value.records[0]).map(x=>[x.code,x.path]));}const {provenance,...annotation}=row;const overlay={...annotation,batch:'synthetic',reviewer:'model:synthetic',reviewedAt:'2026-10-03',evidence:{page:1,quote:'Synthetic evidence'}};for(const quote of ['Synthetic evidence',Array(16).fill('word').join(' '),'保密测试']){overlay.evidence.quote=quote;assert.deepEqual(browser.overlayErrors([overlay]).map(x=>[x.code,x.path]),producer.overlayErrors([overlay]).map(x=>[x.code,x.path]));}console.log(JSON.stringify({cases:changes.length,overlays:3}));`);expect(result).toEqual({cases:12,overlays:3});
});
it('record-only bundles exclude the full-envelope validator and all package imports',async()=>{
 const result=await build({stdin:{contents:`export {snapshotRecordErrors} from ${JSON.stringify(join(out,'identity.ts'))};`,resolveDir:process.cwd(),loader:'ts'},bundle:true,write:false,format:'esm',platform:'browser',target:'es2022',metafile:true});expect(Object.values(result.metafile!.outputs).every(output=>output.imports.length===0)).toBe(true);expect(result.outputFiles[0].text).not.toContain('fullSchemas');expect(result.outputFiles[0].text).not.toContain('kiweeChangelogVersion');
});
