import { expect, test } from 'vitest';
import { readFileSync } from 'node:fs';
import { createIdentity } from '../src/identity.ts';
import { deriveFoundry } from '../src/derive/foundry/index.ts';
import { mappings, observedKeys, systemLeaves } from '../src/derive/foundry/mapping.ts';
import { formula } from '../src/derive/foundry/scales.ts';
import { mergeMechanics } from '../src/derive/foundry/corpus.ts';
import { makeContext } from '../src/derive/structured/common.ts';
import { materialize } from '../src/derive/catalogue.ts';
import { deriveStructured } from '../src/derive/structured/index.ts';
import { schemaErrors } from '../src/validate/index.ts';
import type { Material, Raw } from '../src/derive/catalogue.ts';
import type { AutomationEnvelope, Unsupported } from '../src/protocol.ts';
const material=(kind='feat',raw:Raw={}):Material=>({identity:createIdentity({kind,source:raw.source||'PHB',engName:raw.ENG_name||'Synthetic'}),raw,namespace:'kiwee',files:['synthetic'],expansion:'source'});
const run=(raw:Raw,kind='feat',context:Material[]=[])=>{const row=material(kind,raw);return deriveFoundry({migrationVersion:3,...raw},row,makeContext([row,...context]));};
const fixture=(file:string)=>JSON.parse(readFileSync(`fixtures/g4/${file}.json`,'utf8'));
const envelope=(mechanics:any):AutomationEnvelope=>({schemaVersion:1,protocol:3,versionLock:{kiweeChangelogVersion:'synthetic',kiweeChangelogDate:'2026-10-03',fetchedAt:'2026-10-03T00:00:00Z',foundryMigrationVersion:[3],toolVersion:'test',inputs:[{url:'https://example.org/input.json',path:'input.json',namespace:'synthetic',role:'foundry',sha256:'a'.repeat(64),bytes:1}]},records:[{identity:material().identity,verdict:'needsAnnotation',autoGenerated:true,provenance:[{layer:'foundry',ref:'synthetic'}],unsupported:[],mechanics}]});

// Every whitelist row is exercised as an input field. Dedicated semantic cases below
// verify values, constraints and modes rather than equating presence with automation.
test.each(mappings)('whitelist input $key has a bounded explicit disposition',spec=>{
  const [category,...rest]=spec.key.split(':'),key=rest.join(':'),raw:Raw={};
  if(category==='effect.key')raw.effects=[{transfer:true,changes:[{key,mode:'ADD',value:spec.route==='trait'?spec.target==='conditionImmune'?'charmed':'fire':spec.route==='grant'?'simple':'2'}]}];
  if(category==='system')raw.system={[key]:key==='uses.recovery'?[{period:'lr',type:'recoverAll'}]:key==='uses.max'?'2':'synthetic'};
  if(category==='activity')raw.activities=[{type:key,activation:{type:'action'}}];
  if(category==='advancement')raw.advancement=[{type:key,configuration:{identifier:'synthetic',type:'number',scale:{1:{value:2}}}}];
  if(category==='entryData')raw.entryData={[key]:[]};
  if(category==='flag')raw[key]=true;
  const before=structuredClone(raw),derived=run(raw);
  expect(raw).toEqual(before);expect(derived.decisions.map(d=>d.key)).toContain(spec.key);
  expect(derived.decisions.find(d=>d.key===spec.key)?.route).toBe(spec.route);
  expect(derived.unsupported.some(g=>g.code==='unlisted-foundry-field')).toBe(false);
  expect(schemaErrors(envelope(derived.mechanics))).toEqual([]);
  if(spec.route==='modifier'||spec.route==='hpPerLevel')expect(derived.mechanics.effects![0].changes[0].target).toBe(spec.target);
  if(spec.route==='saveBonus')expect(derived.mechanics.effects![0].changes.map(c=>c.target)).toEqual(['save:str','save:dex','save:con','save:int','save:wis','save:cha']);
  if(spec.route==='unsupported')expect(derived.unsupported).toContainEqual(expect.objectContaining({family:spec.family,code:spec.reason}));
});
test('all observed locked keys, including every >=3-frequency key, have reviewed routes',()=>{
  const inventory=JSON.parse(readFileSync('reports/g1/coverage-report.json','utf8')),counts:Record<string,number>={};
  for(const fields of Object.values(inventory.foundryFieldsByFile) as Record<string,number>[])for(const [key,n]of Object.entries(fields))counts[key]=(counts[key]||0)+n;
  expect(Object.keys(counts).sort()).toEqual(mappings.map(r=>r.key).sort());
  for(const spec of mappings)if(counts[spec.key]>=3)expect(spec.reason).not.toBe('unimplemented-foundry-field');
});
test('effect modes retain numeric semantics; multiply/custom and trait replacement stay deferred',()=>{
  for(const [input,op]of [['ADD','add'],['OVERRIDE','set'],['UPGRADE','max'],['DOWNGRADE','min'],[2,'add'],[5,'set'],[4,'max'],[3,'min']] as const){const r=run({effects:[{transfer:true,changes:[{key:'system.attributes.movement.walk',mode:input,value:'+ 10'}]}]});expect(r.mechanics.modifiers).toEqual([{target:'speed.walk',op,value:10}]);expect(r.mechanics.effects![0].deferred).toBe(true);}
  for(const input of ['CUSTOM','MULTIPLY',0,1]){const r=run({effects:[{transfer:true,changes:[{key:'system.attributes.movement.walk',mode:input,value:'2'}]}]});expect(r.mechanics.modifiers||[]).toEqual([]);expect(r.unsupported.some(g=>g.family==='effectMode')).toBe(true);}
  expect(run({effects:[{transfer:true,changes:[{key:'system.traits.dr.value',mode:'OVERRIDE',value:'fire'}]}]}).unsupported.map(g=>g.code)).toContain('trait-set-replacement-deferred');
});
test('disabled, timed and item effects cannot become unconditional ownership bonuses',()=>{
  const e={transfer:true,changes:[{key:'system.attributes.movement.walk',mode:'ADD',value:10}]};
  for(const effect of [{...e,disabled:true},{...e,duration:{rounds:1}},{...e,flags:{synthetic:true}}])expect(run({effects:[effect]}).mechanics.modifiers||[]).toEqual([]);
  expect(run({effects:[e]},'item').mechanics.modifiers||[]).toEqual([]);
  expect(run(fixture('effects')[0]).mechanics.modifiers||[]).toEqual([]);
});
test('separate spell attack channels do not produce a doubled generic attack bonus',()=>{
  const r=run({effects:[{transfer:true,changes:[{key:'system.bonuses.msak.attack',mode:'ADD',value:1},{key:'system.bonuses.rsak.attack',mode:'ADD',value:1}]}]});
  expect(r.mechanics.modifiers).toEqual([{target:'attack.spellMelee',op:'add',value:1},{target:'attack.spellRanged',op:'add',value:1}]);
});
test('number and dice scales retain sparse tables and a real level-zero baseline',()=>{
  const number=run(fixture('scales')[0],'class'),dice=run(fixture('scales')[1],'race');
  expect(number.mechanics.scales![0].values).toEqual([{level:2,value:2},{level:6,value:3},{level:10,value:4},{level:14,value:5},{level:18,value:6}]);
  expect(dice.mechanics.scales![0].values[0]).toEqual({level:0,dice:{count:1,faces:10}});expect(dice.unsupported.map(g=>g.code)).toContain('dice-scale-roll-deferred');
  expect(formula('@scale.sorcerer.sorcery-points-1',new Map([['sorcery-points','sorcery_points']]))).toBe('@scale.sorcerer.sorcery_points-1');expect(formula('@prof-1')).toBe('@prof-1');expect(formula('@mod')).toBeUndefined();
  const historical=run({advancement:[{type:'ScaleValue',configuration:{identifier:'divine-strike',type:'dice',scale:{8:{n:1,die:8},14:{n:2,die:8}}}}]});expect(historical.mechanics.scales![0].values).toEqual([{level:8,dice:{count:1,faces:8}},{level:14,dice:{count:2,faces:8}}]);
  expect(run({advancement:[{type:'ScaleValue',configuration:{type:'number',scale:{1:{value:2}}}}]}).unsupported.map(g=>g.code)).toContain('scale-definition');
  expect(run({advancement:[{type:'ScaleValue',configuration:{identifier:'incomplete',type:'dice',scale:{1:{faces:8}}}}]}).mechanics.scales||[]).toEqual([]);
});
test('dotted and nested resource objects agree; empty maxima never create usable counters',()=>{
  const dotted=run({system:{'uses.max':'@prof','uses.recovery':[{period:'lr',type:'recoverAll'}]}}),nested=run({system:{uses:{max:'@prof',recovery:[{period:'lr',type:'recoverAll'}]}}});
  expect(dotted.mechanics).toEqual(nested.mechanics);expect(dotted.mechanics.resources![0]).toEqual({key:'foundry:uses',max:{formula:'@prof'},recovery:[{period:'long',amount:'all'}]});
  expect(run({system:{'uses.max':''}}).mechanics.resources||[]).toEqual([]);expect(systemLeaves({uses:{max:2}})).toEqual([['uses.max',2]]);
});
test('only locally declared counters can be consumed; missing, external, negative and translated targets stay deferred',()=>{
  const raw=fixture('activities')[0],r=run(raw);expect(r.mechanics.actions![0].consumes).toEqual({resource:'foundry:uses',amount:1});expect(r.mechanics.actions![0].deferred).toBeUndefined();
  for(const consumes of [{type:'itemUses',value:'1',target:{consumes:{ENG_name:'Synthetic'}}},{type:'attribute',value:'1',target:'原创中文路径'},{type:'itemUses',value:'-1'}]){
    const other=structuredClone(raw);other.activities[0].consumption.targets=[consumes];const result=run(other);expect(result.mechanics.actions![0].consumes).toBeUndefined();expect(result.mechanics.actions![0].deferred).toBe(true);expect(JSON.stringify(result.mechanics)).not.toContain('原创');
  }
});
test('cast resolves complete identities and editions; conditions cannot silently disappear',()=>{
  const spell=material('spell',{ENG_name:'Synthetic Spell',name:'Synthetic Spell',source:'PHB'}),a={type:'cast',activation:{type:'action',condition:'Synthetic gate'},spell:{uuid:'@spell[Synthetic Spell|PHB]'}};
  const r=run({activities:[a]},'feat',[spell]);expect(r.mechanics.actions![0].spell).toBe(spell.identity.key);expect(r.mechanics.actions![0].deferred).toBe(true);
  expect(run({activities:[{...a,spell:{uuid:'@spell[Absent|PHB]'}}]},'feat',[spell]).mechanics.actions||[]).toEqual([]);
});
test('ignore markers and unreviewed migration versions never grant mechanics',()=>{
  const raw=fixture('markers')[0];expect(run(raw).mechanics).toEqual({});expect(run(raw).flags).toEqual(['isIgnored']);
  const future=run({migrationVersion:4,system:{'uses.max':'3'}});expect(future.mechanics).toEqual({});expect(future.unsupported[0].code).toBe('unreviewed-migration-version');
  const unknown=run({effects:[{changes:[{key:'synthetic.unknown',mode:'ADD',value:'2'}]}]});expect(unknown.unsupported.map(g=>g.code)).toContain('unlisted-foundry-field');expect(observedKeys({isIgnored:true})).toEqual(['flag:isIgnored']);
});
test('layer duplicates are deduplicated and conflicting bonuses are identified instead of stacked',()=>{
  const base={modifiers:[{target:'speed.walk',op:'add' as const,value:10}]},gaps:Unsupported[]=[];
  expect(mergeMechanics(base,structuredClone(base),gaps)).toEqual(base);expect(gaps).toEqual([]);
  expect(mergeMechanics(base,{modifiers:[{target:'speed.walk',op:'add',value:20}]},gaps)).toEqual(base);expect(gaps[0].family).toBe('layerConflict');
});
test('Scholar-style expertise alternatives select one group rather than grant every listed skill',()=>{
  const r=run({entryData:{expertise:[{arcana:true},{history:true},{investigation:true},{medicine:true},{nature:true},{religion:true}]}});
  expect(r.mechanics.grants).toHaveLength(6);expect(new Set(r.mechanics.grants!.map(g=>g.setKey))).toEqual(new Set(['expertise:set']));expect(r.mechanics.grants!.map(g=>g.setOption)).toEqual([0,1,2,3,4,5]);
  expect(r.mechanics.grants!.every(g=>g.fixed!.length===1)).toBe(true);
  expect(run({entryData:{skillProficiencies:[{choose:{from:['athletics','survival']}}]}}).mechanics.grants![0].choose).toEqual({count:1,from:['athletics','survival']});
});
test('subrace inheritance accumulates sources while keeping parent alternatives mutually exclusive',()=>{
  const body={race:[{name:'Synthetic Parent',ENG_name:'Synthetic Parent',source:'PHB',skillProficiencies:[{arcana:true},{history:true}]}],subrace:[{name:'Synthetic Child',ENG_name:'Synthetic Child',source:'PHB',raceName:'Synthetic Parent',raceSource:'PHB',skillProficiencies:[{nature:true}]}]},before=structuredClone(body);
  const rows=materialize([{input:{namespace:'kiwee',path:'synthetic',role:'catalog',sha256:'synthetic'},body}]).rows,row=rows.find(r=>r.identity.kind==='subrace')!,grants=deriveStructured(row,makeContext(rows)).mechanics.grants!;
  expect(grants.map(g=>[g.fixed,g.setKey,g.setOption])).toEqual([[['arcana'],'skillProficiencies:parent:set',0],[['history'],'skillProficiencies:parent:set',1],[['nature'],undefined,undefined]]);expect(body).toEqual(before);
});
