import {mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {buildConsumerAdapter} from '../src/runtimeCoverage/adapter.ts';
import {probeEntry} from '../src/runtimeCoverage/probe.ts';
const web=process.argv[2];if(!web)throw Error('Supply pinned Web checkout');mkdirSync('.cache',{recursive:true});
const path=resolve('.cache/probe-test.mjs');await buildConsumerAdapter(web,path,false);const api=await import(pathToFileURL(path).href);
const entry=(id:string,kind:string,raw:any,entries:any[]=[])=>({id,kind,name:id,english:id,source:'PHB',packId:'authored',revision:'fixture',edition:'2014',raw,entries});
const armor=entry('authored-armor','item',{type:'LA',ac:11});
const weapon=entry('authored-weapon','item',{type:'M',weaponCategory:'simple',dmg1:'1d6',dmgType:'B'});
const text=entry('authored-text','feat',{ability:[{str:2}],effects:[{op:'add',target:'hp',value:5}],weight:2},['Unmapped payloads remain manual.']);
const race=entry('authored-race','race',{ability:[{str:2}],speed:{walk:25}});
const cls=entry('authored-class','class',{hd:{faces:10},startingProficiencies:{skills:[{choose:{from:['athletics','arcana'],count:1}}]}});
const choice=entry('authored-choice','feature',{},[{type:'options',count:1,entries:[{type:'entries',name:'Authored option',entries:['A usable selected option.']}]}]);
const unresolved=entry('authored-unresolved','feature',{},[{type:'options',count:1,entries:[{optionalfeature:'missing|PHB'}]}]);
const catalog=[armor,weapon,text,race,cls,choice,unresolved];
assert.equal(probeEntry(api,armor,catalog,[])?.kind,'calculated-sheet');
assert.equal(probeEntry(api,weapon,catalog,[])?.kind,'calculated-weapon');
assert.equal(probeEntry(api,text,catalog,[]),null);
assert.equal(probeEntry(api,race,catalog,[])?.kind,'calculated-sheet');
assert.equal(probeEntry(api,cls,catalog,[])?.kind,'calculated-sheet');
assert.equal(probeEntry(api,choice,catalog,[])?.kind,'choice:content');
assert.equal(probeEntry(api,unresolved,catalog,[]),null);
const parentFeature=entry('parent-resource','feature',{className:'Parent',classSource:'PHB',level:1,resources:[{name:'Parent resource',max:3,recovery:'long'}]});
const parent=entry('Parent','class',{hd:{faces:10},classFeatures:['parent-resource|Parent|PHB|1|PHB']});
const emptyChild=entry('empty-child','subclass',{className:'Parent',classSource:'PHB',subclassFeatures:[]});
const contextual=[...catalog,parent,parentFeature,emptyChild];
const calibration=api.newCharacter('2014');calibration.profile.enabledSources=['PHB'];calibration.automation=api.newAutomationState();calibration.selections=[{id:'parent',entry:parent,level:1,quantity:1,equipped:false}];api.syncFeatures(calibration,contextual);api.syncAutoResources(calibration);assert.ok(Object.values(calibration.runtime.resources).some((r:any)=>r.featureGrant&&r.max===3),'The parent context must actually contain an automatic feature resource');
assert.equal(probeEntry(api,emptyChild,contextual,[parent]),null);
console.log('Runtime probe: 8 real-consumer positive/negative scenarios passed.');
